### ISSUE TITLE
パスワードレス認証への切り替え（認証コード方式）

### ISSUE THREAD

**Issue by TaiyoYamada** [TaiyoYamada/kumatomo#17]
### 概要

新規登録・ログイン画面のUI/UXを改善し、より直感的で親しみやすいデザインにする。
現在のログイン方式（メール＋パスワード）を廃止し、以下のような パスワードレス認証方式 への移行を提案します。

### 改善案

* メールアドレスのみでログイン申請
* 6桁の認証コードをメールで送信
* コード入力により本人確認・ログイン
* セッション管理やトークン付与は従来通り（Sanctumなどを使用）
* メール送信用のSMTPには **Mailhog** を使用予定
* Docker + Laravel Sail 環境下で `mailhog:8025` でUI確認できるように設定する
* `.env` ファイルの設定例：

```env
MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME="Daily Story"
```

* Docker Compose の `docker-compose.yml` に Mailhog を追加する必要あり

---

### Docker Compose に追加する例（備考として）

```yaml
mailhog:
  image: mailhog/mailhog
  ports:
    - "1025:1025" # SMTP
    - "8025:8025" # Web UI
```
